seed: 42
features:
  numeric: [age_months, BMI, muac_cm, head_circumference_cm, dietary_diversity_score, altitude_m, budget_per_day_pen]
  categorical: [sex, region, edema_pitting, anemia_hemoglobin_g_dl, diarrhea_last_2w]
model:
  hidden_layers: [64, 32]
  dropout: 0.2
  lr: 0.001
  epochs: 50
  batch_size: 64
train:
  test_size: 0.2
  stratify: label_status
